"""add test users

Revision ID: 3fe0b09f412b
Revises: c5efe7446a5c
Create Date: 2025-02-03 18:12:49.842549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.utils.utils import get_hash_password

# revision identifiers, used by Alembic.
revision: str = '3fe0b09f412b'
down_revision: Union[str, None] = 'c5efe7446a5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    users = sa.table(
        'users',
        sa.column('user_id', sa.Integer),
        sa.column('fullname', sa.String),
        sa.column('email', sa.String),
        sa.column('password', sa.String),
    )
    user_password = "user12345"

    admin_users = sa.table(
        'admin_users',
        sa.column('user_id', sa.Integer),
        sa.column('fullname', sa.String),
        sa.column('email', sa.String),
        sa.column('password', sa.String),
    )
    admin_user_password = "admin12345"

    accounts = sa.table(
        'accounts',
        sa.column('account_id', sa.Integer),
        sa.column('balance', sa.Float),
        sa.column('user_id', sa.Integer)
    )

    op.bulk_insert(users, [
        {
            "user_id": 1,
            "fullname": "testuser",
            "email": "some@email.com",
            "password": get_hash_password(user_password)
        }
    ])
    op.bulk_insert(admin_users, [
        {
            "user_id": 1,
            "fullname": "testadmin",
            "email": "admin@email.com",
            "password": get_hash_password(admin_user_password)
        }
    ])

    op.bulk_insert(accounts, [
        {
            "account_id": 1,
            "balance": .0,
            "user_id": 1,
        }
    ])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM admin_users WHERE user_id = 1")
    op.execute("DELETE FROM accounts WHERE user_id = 1")
    op.execute("DELETE FROM users WHERE user_id = 1")
    # ### end Alembic commands ###
