"""add column amount for payments

Revision ID: 654d31f801fa
Revises: 3fe0b09f412b
Create Date: 2025-02-03 20:02:39.612427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '654d31f801fa'
down_revision: Union[str, None] = '3fe0b09f412b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('amount', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'amount')
    # ### end Alembic commands ###
